version: "3.8"

services:

  dynamo:
    image: amazon/dynamodb-local
    ports:
      - "8000:8000"
    command: -jar DynamoDBLocal.jar -sharedDb -dbPath /data
    volumes:
      - ./.dynamo_data:/data/
